### ISSUE TITLE
Need help in WebOdf configuration for 4.2.c

### ISSUE THREAD

**Issue by pillais1** [share-extras/media-viewers#34] opened 2013-11-28 17:56 UTC
Can someone please let me know what configuration I am missing for WebOdf preview. Below are the steps I followed:
1. Placed media-viewers-2.5.1.jar, share-webodf.jar under tomcat/share/lib
2. Placed web-preview.get.config.xml under tomcat\shared\classes\alfresco\web-extension\site-webscripts\org\alfresco\components\preview

Hope so we just need to add this xml snippet in web-preview.get.config.xml
      <condition mimeType="application/vnd.oasis.opendocument.text">
         <plugin testPluginAvailability="true">WebODF</plugin>
      </condition>

When I try to preview any *.odt file it shows the preview in PDFJs viewer by converting .odt > pdf in back instead of WebOdf viewer.

**Comment by wabson** [comment] 2013-11-28 18:39
Did you install the actual WebODF library JAR too? To link to download this
is in the installation instructions in the README.

**Comment by pillais1** [comment] 2013-11-29 13:08
Are you reffering to  share-webodf.jar?

If not can you please share the URL to download the WebODF library JAR?

**Comment by wabson** [comment] 2013-11-29 18:27
That is the one. DId you also enable the 'WebODF Viewer (Experimental)' extensibility module in Share?

The 'WebODF Configuration' module can be used in place of the XML configuration in 4.2.c and upwards, and is probably going to be more reliable for you.

**Comment by tbaptista** [comment] 2013-12-14 00:13
Have the same problem. Did you manage to solve the issue?

**Comment by wabson** [comment] 2013-12-20 17:37
I reproduced this issue when the _PDfJs Configuration_ module was loaded **after** the _WebODF Configuration_ module in the deployment console. This is by design, as those modules always insert the viewer at the start of the chain.

You can use the _Up_ and _Down_ buttons to rearrange the modules so that WebODF comes after and apply the changes, you should then find that the WebODF viewer is used for ODT documents.

![screen shot 2013-12-20 at 17 30 46](https://f.cloud.github.com/assets/1727487/1792315/15ec3d34-699d-11e3-85a8-71fc8c7b9696.png)

Incidentally if you find the WebODF viewer useful and want to contribute to making it a bit better, that would be very welcome.

**Comment by wabson** [comment] 2013-12-27 16:06
Closing as notabug

**Closed as completed by wabson** 2013-12-27 16:06 UTC
Labels: notabug
