### ISSUE TITLE
InvalidCharacterError: 'btoa' failed

### ISSUE THREAD

**Issue by jirutka** [share-extras/media-viewers#32] opened 2013-11-14 14:36 UTC
When I open a document page, MediaViewer loads (navigation bar, white “paper”, …), but the actual document doesn’t load (progress wheel is spinning). JavaScript console shows:

``` javascript
Uncaught InvalidCharacterError: 'btoa' failed: The string to be encoded contains characters outside of the Latin1 range. pdf_a3cc7a581acd09127d38c3ae6b3bb.js:496
fontLoaderPrepareFontLoadEvent pdf_a3cc7a581acd09127d38c3ae6b3bb.js:496
fontLoaderBind pdf_a3cc7a581acd09127d38c3ae6b3bb.js:483
transportObj pdf_a3cc7a581acd09127d38c3ae6b3bb.js:343
messageHandlerComObjOnMessage
```

And there’s some context:

``` javascript
if (i < loadTestFontId.length) {
    checksum = (checksum - XXXX_VALUE +
        int32(loadTestFontId + 'XXX', i)) | 0;
}
data = spliceString(data, CFF_CHECKSUM_OFFSET, 4, string32(checksum));
> var url = 'url(data:font/opentype;base64,' + btoa(data) + ');';
var rule = '@font-face { font-family:"' + loadTestFontId + '";src:' +
    url + '}';
FontLoader.insertRule(rule);
var names = [];
for (i = 0, ii = fonts.length; i < ii; i++) {
    names.push(fonts[i].loadedName);
}
```

The weird thing is that it’s failing only _somewhere_. It seems that there’s no problem in Firefox (regardless of the platform), but some people with Chrome has problem.

**Comment by loftux** [comment] 2013-11-14 14:58
From the code you have pasted it looks like the error is in pdf.js code. This is a library we use as is. However, we are not always on the latest version.
Can you please try your pdf here
http://mozilla.github.io/pdf.js/web/viewer.html
If you still see the same error, report it to https://github.com/mozilla/pdf.js project.
If not, we may need to update to a later version of the external pdf.js lib.

**Comment by wabson** [comment] 2013-12-11 12:53
Since no further feedback has been received, this issue will be closed shortly. Please reply in this thread if this is still an issue and you are able to provide the information requested or a copy of the problem file.

**Comment by charnog** [comment] 2013-12-16 05:42
@jirutka in pdf.js try to find...

``` javascript
var loadTestFontId = 'lt' + Date.now() + this.loadTestFontId++;
```

And replace it with...

``` javascript
var loadTestFontId = 'lt' + (+Date.now()) + this.loadTestFontId++;
```

It can happen when the Date.now method is overloaded to return a Date instance instead of UNIX-milliseconds.

**Comment by loftux** [comment] 2013-12-16 09:14
@charnog Since this seems to be a bug in the external library pdf.js, can you please report this to the pdf.js (https://github.com/mozilla/pdf.js) project? We try to avoid using custom versions of their library. Once fixed by the pdf.js project I will update the included library.

**Comment by charnog** [comment] 2013-12-17 05:45
@loftux it's not a pdf.js or a media-viewers bug. According to [15.9.4.4](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.4.4) "The now function return a Number value...". So the polyfill MUST return a Number value too.

``` javascript
if (!Date.now) {
  Date.now = function now() {
    return new Date().getTime();
  };
}
```

**Comment by wabson** [comment] 2014-01-14 10:28
Not a bug with the media-viewers project

**Closed as completed by wabson** 2014-01-14 10:28 UTC
Labels: notabug
