### ISSUE TITLE
Does not work in 4.2.d

### ISSUE THREAD

**Issue by tara-herman** [share-extras/media-viewers#30] opened 2013-10-31 14:01 UTC
Great extension - I love using it for my 4.2.c Alfresco projects, however it's not working in 4.2.d. The preview screen remains an empty grey box. No error messages appear.

Thanks for all of your great work on this extension so far!

**Comment by wabson** [comment] 2013-10-31 15:02
Which version are you using? Did you pull the latest code from Git?

**Comment by slibert** [comment] 2013-10-31 15:25
There was a similar bug in MediaViewers 2.5.1, I suppose 2.6 correct it but did not test it by myself.
By the way, fix can be found here : https://github.com/share-extras/media-viewers/issues/5

**Comment by wabson** [comment] 2013-10-31 16:01
Thanks for confirming, and yes I agree that 2.6 fixes this and has now been released. Closing as duplicate of #5.

**Closed as completed by wabson** 2013-10-31 16:01 UTC
Labels: bug, duplicate

**Comment by tara-herman** [comment] 2013-10-31 16:40
Sorry Will - I didn't notice the other post. I'm sorry to have wasted your time. I'll apply the fix as suggested.

Thanks again for such an awesome project!
